/*
 * gateway.marvel.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.usj.mastertsa.jhernandez.musicquiz.client.model;

import java.io.Serializable;
import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.CharacterList;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.ComicList;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.CreatorList;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.EventSummary;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.Image;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.SeriesList;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.StoryList;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.Url;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Event
 */

public class Event implements Serializable {
  public static final String JSON_PROPERTY_CHARACTERS = "characters";
  private CharacterList characters;

  public static final String JSON_PROPERTY_COMICS = "comics";
  private ComicList comics;

  public static final String JSON_PROPERTY_CREATORS = "creators";
  private CreatorList creators;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_END = "end";
  private String end;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  private String modified;

  public static final String JSON_PROPERTY_NEXT = "next";
  private EventSummary next;

  public static final String JSON_PROPERTY_PREVIOUS = "previous";
  private EventSummary previous;

  public static final String JSON_PROPERTY_RESOURCE_U_R_I = "resourceURI";
  private String resourceURI;

  public static final String JSON_PROPERTY_SERIES = "series";
  private SeriesList series;

  public static final String JSON_PROPERTY_START = "start";
  private String start;

  public static final String JSON_PROPERTY_STORIES = "stories";
  private StoryList stories;

  public static final String JSON_PROPERTY_THUMBNAIL = "thumbnail";
  private Image thumbnail;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_URLS = "urls";
  private List<Url> urls = null;


  public Event characters(CharacterList characters) {
    
    this.characters = characters;
    return this;
  }

   /**
   * Get characters
   * @return characters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHARACTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CharacterList getCharacters() {
    return characters;
  }



  public void setCharacters(CharacterList characters) {
    this.characters = characters;
  }


  public Event comics(ComicList comics) {
    
    this.comics = comics;
    return this;
  }

   /**
   * Get comics
   * @return comics
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COMICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ComicList getComics() {
    return comics;
  }



  public void setComics(ComicList comics) {
    this.comics = comics;
  }


  public Event creators(CreatorList creators) {
    
    this.creators = creators;
    return this;
  }

   /**
   * Get creators
   * @return creators
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreatorList getCreators() {
    return creators;
  }



  public void setCreators(CreatorList creators) {
    this.creators = creators;
  }


  public Event description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * A description of the event.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A description of the event.")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }



  public void setDescription(String description) {
    this.description = description;
  }


  public Event end(String end) {
    
    this.end = end;
    return this;
  }

   /**
   * The date of publication of the last issue in this event.
   * @return end
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date of publication of the last issue in this event.")
  @JsonProperty(JSON_PROPERTY_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEnd() {
    return end;
  }



  public void setEnd(String end) {
    this.end = end;
  }


  public Event id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * The unique ID of the event resource.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique ID of the event resource.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  public void setId(Integer id) {
    this.id = id;
  }


  public Event modified(String modified) {
    
    this.modified = modified;
    return this;
  }

   /**
   * The date the resource was most recently modified.
   * @return modified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date the resource was most recently modified.")
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModified() {
    return modified;
  }



  public void setModified(String modified) {
    this.modified = modified;
  }


  public Event next(EventSummary next) {
    
    this.next = next;
    return this;
  }

   /**
   * Get next
   * @return next
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventSummary getNext() {
    return next;
  }



  public void setNext(EventSummary next) {
    this.next = next;
  }


  public Event previous(EventSummary previous) {
    
    this.previous = previous;
    return this;
  }

   /**
   * Get previous
   * @return previous
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PREVIOUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventSummary getPrevious() {
    return previous;
  }



  public void setPrevious(EventSummary previous) {
    this.previous = previous;
  }


  public Event resourceURI(String resourceURI) {
    
    this.resourceURI = resourceURI;
    return this;
  }

   /**
   * The canonical URL identifier for this resource.
   * @return resourceURI
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The canonical URL identifier for this resource.")
  @JsonProperty(JSON_PROPERTY_RESOURCE_U_R_I)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResourceURI() {
    return resourceURI;
  }



  public void setResourceURI(String resourceURI) {
    this.resourceURI = resourceURI;
  }


  public Event series(SeriesList series) {
    
    this.series = series;
    return this;
  }

   /**
   * Get series
   * @return series
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SeriesList getSeries() {
    return series;
  }



  public void setSeries(SeriesList series) {
    this.series = series;
  }


  public Event start(String start) {
    
    this.start = start;
    return this;
  }

   /**
   * The date of publication of the first issue in this event.
   * @return start
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date of publication of the first issue in this event.")
  @JsonProperty(JSON_PROPERTY_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStart() {
    return start;
  }



  public void setStart(String start) {
    this.start = start;
  }


  public Event stories(StoryList stories) {
    
    this.stories = stories;
    return this;
  }

   /**
   * Get stories
   * @return stories
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STORIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StoryList getStories() {
    return stories;
  }



  public void setStories(StoryList stories) {
    this.stories = stories;
  }


  public Event thumbnail(Image thumbnail) {
    
    this.thumbnail = thumbnail;
    return this;
  }

   /**
   * Get thumbnail
   * @return thumbnail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_THUMBNAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Image getThumbnail() {
    return thumbnail;
  }



  public void setThumbnail(Image thumbnail) {
    this.thumbnail = thumbnail;
  }


  public Event title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * The title of the event.
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The title of the event.")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }



  public void setTitle(String title) {
    this.title = title;
  }


  public Event urls(List<Url> urls) {
    
    this.urls = urls;
    return this;
  }

  public Event addUrlsItem(Url urlsItem) {
    if (this.urls == null) {
      this.urls = new ArrayList<Url>();
    }
    this.urls.add(urlsItem);
    return this;
  }

   /**
   * A set of public web site URLs for the event.
   * @return urls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A set of public web site URLs for the event.")
  @JsonProperty(JSON_PROPERTY_URLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Url> getUrls() {
    return urls;
  }



  public void setUrls(List<Url> urls) {
    this.urls = urls;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Event event = (Event) o;
    return Objects.equals(this.characters, event.characters) &&
        Objects.equals(this.comics, event.comics) &&
        Objects.equals(this.creators, event.creators) &&
        Objects.equals(this.description, event.description) &&
        Objects.equals(this.end, event.end) &&
        Objects.equals(this.id, event.id) &&
        Objects.equals(this.modified, event.modified) &&
        Objects.equals(this.next, event.next) &&
        Objects.equals(this.previous, event.previous) &&
        Objects.equals(this.resourceURI, event.resourceURI) &&
        Objects.equals(this.series, event.series) &&
        Objects.equals(this.start, event.start) &&
        Objects.equals(this.stories, event.stories) &&
        Objects.equals(this.thumbnail, event.thumbnail) &&
        Objects.equals(this.title, event.title) &&
        Objects.equals(this.urls, event.urls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(characters, comics, creators, description, end, id, modified, next, previous, resourceURI, series, start, stories, thumbnail, title, urls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Event {\n");
    sb.append("    characters: ").append(toIndentedString(characters)).append("\n");
    sb.append("    comics: ").append(toIndentedString(comics)).append("\n");
    sb.append("    creators: ").append(toIndentedString(creators)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    previous: ").append(toIndentedString(previous)).append("\n");
    sb.append("    resourceURI: ").append(toIndentedString(resourceURI)).append("\n");
    sb.append("    series: ").append(toIndentedString(series)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    stories: ").append(toIndentedString(stories)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    urls: ").append(toIndentedString(urls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

