/*
 * gateway.marvel.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.usj.mastertsa.jhernandez.musicquiz.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.CharacterList;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.ComicList;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.ComicSummary;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.CreatorList;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.EventList;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.Image;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.SeriesList;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Story
 */

public class Story {
  public static final String JSON_PROPERTY_CHARACTERS = "characters";
  private CharacterList characters;

  public static final String JSON_PROPERTY_COMICS = "comics";
  private ComicList comics;

  public static final String JSON_PROPERTY_CREATORS = "creators";
  private CreatorList creators;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_EVENTS = "events";
  private EventList events;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_MODIFIED = "modified";
  private String modified;

  public static final String JSON_PROPERTY_ORIGINALISSUE = "originalissue";
  private ComicSummary originalissue;

  public static final String JSON_PROPERTY_RESOURCE_U_R_I = "resourceURI";
  private String resourceURI;

  public static final String JSON_PROPERTY_SERIES = "series";
  private SeriesList series;

  public static final String JSON_PROPERTY_THUMBNAIL = "thumbnail";
  private Image thumbnail;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;


  public Story characters(CharacterList characters) {
    
    this.characters = characters;
    return this;
  }

   /**
   * Get characters
   * @return characters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CHARACTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CharacterList getCharacters() {
    return characters;
  }



  public void setCharacters(CharacterList characters) {
    this.characters = characters;
  }


  public Story comics(ComicList comics) {
    
    this.comics = comics;
    return this;
  }

   /**
   * Get comics
   * @return comics
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COMICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ComicList getComics() {
    return comics;
  }



  public void setComics(ComicList comics) {
    this.comics = comics;
  }


  public Story creators(CreatorList creators) {
    
    this.creators = creators;
    return this;
  }

   /**
   * Get creators
   * @return creators
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CREATORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreatorList getCreators() {
    return creators;
  }



  public void setCreators(CreatorList creators) {
    this.creators = creators;
  }


  public Story description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * A short description of the story.
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A short description of the story.")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }



  public void setDescription(String description) {
    this.description = description;
  }


  public Story events(EventList events) {
    
    this.events = events;
    return this;
  }

   /**
   * Get events
   * @return events
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventList getEvents() {
    return events;
  }



  public void setEvents(EventList events) {
    this.events = events;
  }


  public Story id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * The unique ID of the story resource.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique ID of the story resource.")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }



  public void setId(Integer id) {
    this.id = id;
  }


  public Story modified(String modified) {
    
    this.modified = modified;
    return this;
  }

   /**
   * The date the resource was most recently modified.
   * @return modified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date the resource was most recently modified.")
  @JsonProperty(JSON_PROPERTY_MODIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModified() {
    return modified;
  }



  public void setModified(String modified) {
    this.modified = modified;
  }


  public Story originalissue(ComicSummary originalissue) {
    
    this.originalissue = originalissue;
    return this;
  }

   /**
   * Get originalissue
   * @return originalissue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ORIGINALISSUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ComicSummary getOriginalissue() {
    return originalissue;
  }



  public void setOriginalissue(ComicSummary originalissue) {
    this.originalissue = originalissue;
  }


  public Story resourceURI(String resourceURI) {
    
    this.resourceURI = resourceURI;
    return this;
  }

   /**
   * The canonical URL identifier for this resource. 
   * @return resourceURI
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The canonical URL identifier for this resource. ")
  @JsonProperty(JSON_PROPERTY_RESOURCE_U_R_I)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResourceURI() {
    return resourceURI;
  }



  public void setResourceURI(String resourceURI) {
    this.resourceURI = resourceURI;
  }


  public Story series(SeriesList series) {
    
    this.series = series;
    return this;
  }

   /**
   * Get series
   * @return series
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SERIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SeriesList getSeries() {
    return series;
  }



  public void setSeries(SeriesList series) {
    this.series = series;
  }


  public Story thumbnail(Image thumbnail) {
    
    this.thumbnail = thumbnail;
    return this;
  }

   /**
   * Get thumbnail
   * @return thumbnail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_THUMBNAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Image getThumbnail() {
    return thumbnail;
  }



  public void setThumbnail(Image thumbnail) {
    this.thumbnail = thumbnail;
  }


  public Story title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * The story title.
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The story title.")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }



  public void setTitle(String title) {
    this.title = title;
  }


  public Story type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * The story type e.g. interior story, cover, text story.
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The story type e.g. interior story, cover, text story.")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }



  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Story story = (Story) o;
    return Objects.equals(this.characters, story.characters) &&
        Objects.equals(this.comics, story.comics) &&
        Objects.equals(this.creators, story.creators) &&
        Objects.equals(this.description, story.description) &&
        Objects.equals(this.events, story.events) &&
        Objects.equals(this.id, story.id) &&
        Objects.equals(this.modified, story.modified) &&
        Objects.equals(this.originalissue, story.originalissue) &&
        Objects.equals(this.resourceURI, story.resourceURI) &&
        Objects.equals(this.series, story.series) &&
        Objects.equals(this.thumbnail, story.thumbnail) &&
        Objects.equals(this.title, story.title) &&
        Objects.equals(this.type, story.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(characters, comics, creators, description, events, id, modified, originalissue, resourceURI, series, thumbnail, title, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Story {\n");
    sb.append("    characters: ").append(toIndentedString(characters)).append("\n");
    sb.append("    comics: ").append(toIndentedString(comics)).append("\n");
    sb.append("    creators: ").append(toIndentedString(creators)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    originalissue: ").append(toIndentedString(originalissue)).append("\n");
    sb.append("    resourceURI: ").append(toIndentedString(resourceURI)).append("\n");
    sb.append("    series: ").append(toIndentedString(series)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

