/*
 * gateway.marvel.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.usj.mastertsa.jhernandez.musicquiz.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TextObject
 */

public class TextObject {
  public static final String JSON_PROPERTY_LANGUAGE = "language";
  private String language;

  public static final String JSON_PROPERTY_TEXT = "text";
  private String text;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;


  public TextObject language(String language) {
    
    this.language = language;
    return this;
  }

   /**
   * The IETF language tag denoting the language the text object is written in.
   * @return language
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The IETF language tag denoting the language the text object is written in.")
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLanguage() {
    return language;
  }



  public void setLanguage(String language) {
    this.language = language;
  }


  public TextObject text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * The text.
   * @return text
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The text.")
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getText() {
    return text;
  }



  public void setText(String text) {
    this.text = text;
  }


  public TextObject type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * The canonical type of the text object (e.g. solicit text, preview text, etc.).
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The canonical type of the text object (e.g. solicit text, preview text, etc.).")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }



  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TextObject textObject = (TextObject) o;
    return Objects.equals(this.language, textObject.language) &&
        Objects.equals(this.text, textObject.text) &&
        Objects.equals(this.type, textObject.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, text, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TextObject {\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

