/*
 * gateway.marvel.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.usj.mastertsa.jhernandez.musicquiz.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.ComicList;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.EventList;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.Image;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.SeriesList;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.StoryList;
import es.usj.mastertsa.jhernandez.musicquiz.client.model.Url;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Creator
 */
public class CreatorTest {
    private final Creator model = new Creator();

    /**
     * Model tests for Creator
     */
    @Test
    public void testCreator() {
        // TODO: test Creator
    }

    /**
     * Test the property 'comics'
     */
    @Test
    public void comicsTest() {
        // TODO: test comics
    }

    /**
     * Test the property 'events'
     */
    @Test
    public void eventsTest() {
        // TODO: test events
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'fullName'
     */
    @Test
    public void fullNameTest() {
        // TODO: test fullName
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'middleName'
     */
    @Test
    public void middleNameTest() {
        // TODO: test middleName
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'resourceURI'
     */
    @Test
    public void resourceURITest() {
        // TODO: test resourceURI
    }

    /**
     * Test the property 'series'
     */
    @Test
    public void seriesTest() {
        // TODO: test series
    }

    /**
     * Test the property 'stories'
     */
    @Test
    public void storiesTest() {
        // TODO: test stories
    }

    /**
     * Test the property 'suffix'
     */
    @Test
    public void suffixTest() {
        // TODO: test suffix
    }

    /**
     * Test the property 'thumbnail'
     */
    @Test
    public void thumbnailTest() {
        // TODO: test thumbnail
    }

    /**
     * Test the property 'urls'
     */
    @Test
    public void urlsTest() {
        // TODO: test urls
    }

}
