/*
 * gateway.marvel.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.usj.mastertsa.pluengo.marvelcollection.client.model;

import org.junit.Test;


/**
 * Model tests for CharacterDataWrapper
 */
public class CharacterDataWrapperTest {
    private final CharacterDataWrapper model = new CharacterDataWrapper();

    /**
     * Model tests for CharacterDataWrapper
     */
    @Test
    public void testCharacterDataWrapper() {
        // TODO: test CharacterDataWrapper
    }

    /**
     * Test the property 'attributionHTML'
     */
    @Test
    public void attributionHTMLTest() {
        // TODO: test attributionHTML
    }

    /**
     * Test the property 'attributionText'
     */
    @Test
    public void attributionTextTest() {
        // TODO: test attributionText
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'copyright'
     */
    @Test
    public void copyrightTest() {
        // TODO: test copyright
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'etag'
     */
    @Test
    public void etagTest() {
        // TODO: test etag
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
