/*
 * gateway.marvel.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.usj.mastertsa.pluengo.marvelcollection.client.model;

import org.junit.Test;


/**
 * Model tests for CharacterList
 */
public class CharacterListTest {
    private final CharacterList model = new CharacterList();

    /**
     * Model tests for CharacterList
     */
    @Test
    public void testCharacterList() {
        // TODO: test CharacterList
    }

    /**
     * Test the property 'available'
     */
    @Test
    public void availableTest() {
        // TODO: test available
    }

    /**
     * Test the property 'collectionURI'
     */
    @Test
    public void collectionURITest() {
        // TODO: test collectionURI
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'returned'
     */
    @Test
    public void returnedTest() {
        // TODO: test returned
    }

}
