/*
 * gateway.marvel.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.usj.mastertsa.pluengo.marvelcollection.client.model;

import org.junit.Test;


/**
 * Model tests for ComicDate
 */
public class ComicDateTest {
    private final ComicDate model = new ComicDate();

    /**
     * Model tests for ComicDate
     */
    @Test
    public void testComicDate() {
        // TODO: test ComicDate
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
