/*
 * gateway.marvel.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.usj.mastertsa.pluengo.marvelcollection.client.model;

import org.junit.Test;


/**
 * Model tests for Comic
 */
public class ComicTest {
    private final Comic model = new Comic();

    /**
     * Model tests for Comic
     */
    @Test
    public void testComic() {
        // TODO: test Comic
    }

    /**
     * Test the property 'characters'
     */
    @Test
    public void charactersTest() {
        // TODO: test characters
    }

    /**
     * Test the property 'collectedIssues'
     */
    @Test
    public void collectedIssuesTest() {
        // TODO: test collectedIssues
    }

    /**
     * Test the property 'collections'
     */
    @Test
    public void collectionsTest() {
        // TODO: test collections
    }

    /**
     * Test the property 'creators'
     */
    @Test
    public void creatorsTest() {
        // TODO: test creators
    }

    /**
     * Test the property 'dates'
     */
    @Test
    public void datesTest() {
        // TODO: test dates
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'diamondCode'
     */
    @Test
    public void diamondCodeTest() {
        // TODO: test diamondCode
    }

    /**
     * Test the property 'digitalId'
     */
    @Test
    public void digitalIdTest() {
        // TODO: test digitalId
    }

    /**
     * Test the property 'ean'
     */
    @Test
    public void eanTest() {
        // TODO: test ean
    }

    /**
     * Test the property 'events'
     */
    @Test
    public void eventsTest() {
        // TODO: test events
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'images'
     */
    @Test
    public void imagesTest() {
        // TODO: test images
    }

    /**
     * Test the property 'isbn'
     */
    @Test
    public void isbnTest() {
        // TODO: test isbn
    }

    /**
     * Test the property 'issn'
     */
    @Test
    public void issnTest() {
        // TODO: test issn
    }

    /**
     * Test the property 'issueNumber'
     */
    @Test
    public void issueNumberTest() {
        // TODO: test issueNumber
    }

    /**
     * Test the property 'modified'
     */
    @Test
    public void modifiedTest() {
        // TODO: test modified
    }

    /**
     * Test the property 'pageCount'
     */
    @Test
    public void pageCountTest() {
        // TODO: test pageCount
    }

    /**
     * Test the property 'prices'
     */
    @Test
    public void pricesTest() {
        // TODO: test prices
    }

    /**
     * Test the property 'resourceURI'
     */
    @Test
    public void resourceURITest() {
        // TODO: test resourceURI
    }

    /**
     * Test the property 'series'
     */
    @Test
    public void seriesTest() {
        // TODO: test series
    }

    /**
     * Test the property 'stories'
     */
    @Test
    public void storiesTest() {
        // TODO: test stories
    }

    /**
     * Test the property 'textObjects'
     */
    @Test
    public void textObjectsTest() {
        // TODO: test textObjects
    }

    /**
     * Test the property 'thumbnail'
     */
    @Test
    public void thumbnailTest() {
        // TODO: test thumbnail
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'upc'
     */
    @Test
    public void upcTest() {
        // TODO: test upc
    }

    /**
     * Test the property 'urls'
     */
    @Test
    public void urlsTest() {
        // TODO: test urls
    }

    /**
     * Test the property 'variantDescription'
     */
    @Test
    public void variantDescriptionTest() {
        // TODO: test variantDescription
    }

    /**
     * Test the property 'variants'
     */
    @Test
    public void variantsTest() {
        // TODO: test variants
    }

}
