/*
 * gateway.marvel.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.usj.mastertsa.pluengo.marvelcollection.client.model;

import org.junit.Test;


/**
 * Model tests for SeriesSummary
 */
public class SeriesSummaryTest {
    private final SeriesSummary model = new SeriesSummary();

    /**
     * Model tests for SeriesSummary
     */
    @Test
    public void testSeriesSummary() {
        // TODO: test SeriesSummary
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'resourceURI'
     */
    @Test
    public void resourceURITest() {
        // TODO: test resourceURI
    }

}
