/*
 * gateway.marvel.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: Cable
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.usj.mastertsa.pluengo.marvelcollection.client.model;

import org.junit.Test;


/**
 * Model tests for StorySummary
 */
public class StorySummaryTest {
    private final StorySummary model = new StorySummary();

    /**
     * Model tests for StorySummary
     */
    @Test
    public void testStorySummary() {
        // TODO: test StorySummary
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'resourceURI'
     */
    @Test
    public void resourceURITest() {
        // TODO: test resourceURI
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
